# This file was generated by GoReleaser. DO NOT EDIT.
cask "m365crawl" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "633a06bf491a3e6f6d3225c8b1c7a4c2a26f7104f6e153ba19c3e92bd6b8ee3b"
      url "https://github.com/ourostack/m365crawl/releases/download/v#{version}/m365crawl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6bcc6915f18d091e8c245e5dcb00ec9c47472dced6b2d1b2835065705f2800d1"
      url "https://github.com/ourostack/m365crawl/releases/download/v#{version}/m365crawl_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "m365crawl"
  desc "Mirror the Microsoft Teams desktop cache into local SQLite for agents. Read-only, offline, no tokens."
  homepage "https://github.com/ourostack/m365crawl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "m365crawl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/m365crawl"]
    end
  end

  # No zap stanza required
end
