# This file was generated by GoReleaser. DO NOT EDIT.
cask "m365crawl" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "ca5452f41ef726c53c9215b1f2132e437710171521adcc6469d977fb91005caa"
      url "https://github.com/ourostack/m365crawl/releases/download/v#{version}/m365crawl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d74332aef03f25d087783af1ae7159b47460031bd104a2cf8dbe11261d369d9a"
      url "https://github.com/ourostack/m365crawl/releases/download/v#{version}/m365crawl_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "m365crawl"
  desc "Mirror the Microsoft Teams desktop cache into local SQLite for agents. Read-only, offline, no tokens."
  homepage "https://github.com/ourostack/m365crawl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "m365crawl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/m365crawl"]
    end
  end

  # No zap stanza required
end
