# This file was generated by GoReleaser. DO NOT EDIT.
cask "m365crawl" do
  version "0.5.0-rc.1"

  on_macos do
    on_arm do
      sha256 "a1dd7d4b54619bbc139a966b34501a488a70f1e70e7be683f731664ec943b1d5"
      url "https://github.com/ourostack/m365crawl/releases/download/v#{version}/m365crawl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa3749de067df7c64706b8351525613e5a2cca70aa4f0bddcebc0dad5257f153"
      url "https://github.com/ourostack/m365crawl/releases/download/v#{version}/m365crawl_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "m365crawl"
  desc "Mirror the Microsoft Teams desktop cache into local SQLite for agents. Read-only, offline, no tokens."
  homepage "https://github.com/ourostack/m365crawl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "m365crawl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/m365crawl"]
    end
  end

  # No zap stanza required
end
