# This file was generated by GoReleaser. DO NOT EDIT.
cask "teamscrawl" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "6165fec7fca1f36d08d88fb21270db5d516957c87e504df0d0490d06ff038bce"
      url "https://github.com/ourostack/teamscrawl/releases/download/v#{version}/teamscrawl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ceab332bd45c21024132b2d05d29f7181c23ee5ea743ed52b16aaf3fde3c3538"
      url "https://github.com/ourostack/teamscrawl/releases/download/v#{version}/teamscrawl_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "teamscrawl"
  desc "Mirror the Microsoft Teams desktop cache into local SQLite for agents. Read-only, offline, no tokens."
  homepage "https://github.com/ourostack/teamscrawl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teamscrawl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/teamscrawl"]
    end
  end

  # No zap stanza required
end
