# This file was generated by GoReleaser. DO NOT EDIT.
cask "teamscrawl" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "475b79c34fccaff5fb4348946fb87140f0e4a5b130902dba22e67a0415fc4012"
      url "https://github.com/ourostack/teamscrawl/releases/download/v#{version}/teamscrawl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "36a6092ee3af9ea0b43d5c6982b9f7ce3c15edb11a2f13985f1c18bea93d90f6"
      url "https://github.com/ourostack/teamscrawl/releases/download/v#{version}/teamscrawl_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "teamscrawl"
  desc "Mirror the Microsoft Teams desktop cache into local SQLite for agents. Read-only, offline, no tokens."
  homepage "https://github.com/ourostack/teamscrawl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teamscrawl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/teamscrawl"]
    end
  end

  # No zap stanza required
end
