# This file was generated by GoReleaser. DO NOT EDIT.
cask "teamscrawl" do
  version "0.4.0-rc.2"

  on_macos do
    on_arm do
      sha256 "8886ce685d0649aea4658b3beb0fd46e21666878c3e2750520eef964e25718c3"
      url "https://github.com/ourostack/teamscrawl/releases/download/v#{version}/teamscrawl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8463c3347274a438456ccce2ab792e421e65929410f42e197aed5b9e432941e5"
      url "https://github.com/ourostack/teamscrawl/releases/download/v#{version}/teamscrawl_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "teamscrawl"
  desc "Mirror the Microsoft Teams desktop cache into local SQLite for agents. Read-only, offline, no tokens."
  homepage "https://github.com/ourostack/teamscrawl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teamscrawl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/teamscrawl"]
    end
  end

  # No zap stanza required
end
